### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by codegoblins**

### CODE REVIEW

**Comment by mmedal** [comment]
We can certainly discuss this change to the code base, but the grammar in its current state is still correct. Forward/s can be used interchangeably as adverbs, with "forward" being more popular in the American-English and "forwards" being more popular in UK-English. I happen to tend towards (or toward for Americans like yourself) British spellings and grammar.

**Comment by codegoblins** [comment]
Are there any plans to internationalize (or internationalise for Brits like yourself) the site? Of course it may have to happen client side since I don't think you have access the `Accept-Language` header with Github Pages

**Comment by scott113341** [comment]
Please make sure the tests pass locally before submitting a PR.  It is really disrespectful to the maintainer to submit a PR with failing tests... recommend closing this @mmedal to teach this clown a lesson.

**Comment by codegoblins** [comment]
@mmedal @scott113341 looks like the travis hook should be disabled for PRs, since it is trying to immediately push to `gh-pages`

**Comment by mmedal** [comment]
The issue concerning auto-builds on pull-requests has been resolved.

**Pull request closed without merging**
